apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: i9z6ntl65-python 
  janus-idp.io/tekton: i9z6ntl65-python
  backstage.io/kubernetes-id: i9z6ntl65-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: i9z6ntl65-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml